### ISSUE TITLE
Navigating straight to nation info returns 404

### ISSUE THREAD

**Issue by vuolen** [osakunta/website#23]
Steps to reproduce:

1. Go to https://uusi.satakuntalainenosakunta.fi/nation-info
2. Returns 404

Navigating through the home page and nav bar still works

**Comment by YB-BigSwan** [comment]
Have not had this issue when navigating via localhost or the preview link. Good to know the "uusi" url exists. Will do some investigation on Monday.

**Comment by YB-BigSwan** [comment]
Firebase may need to be configured to handle Next's dynamic routing
